name: EC2 instance running using github actions flask
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws_key.pem
                  chmod 600 ~/.ssh/aws_key.pem

            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

                  sudo apt update
                  sudo apt install git python3-venv -y

                  # Remove old repo if exists
                  rm -rf Github_Actions


                  git clone https://github.com/sureshsoudararajan/Github_Actions.git
                  cd Github_Actions

                  # Create virtual env
                  python3 -m venv venv
                  source venv/bin/activate

                  pip install flask

                  # Kill old process
                  pkill -f main.py || true

                  # Run app
                  nohup python3 main.py > flask_app.log 2>&1 &

                  EOF
