name: Email Send
on: push

jobs:
  sendmail:
    runs-on: ubuntu-22.04

    steps:
      - name: Send mail to friend
        run: echo "Hello Friend"
        
      - name: configuration to send mail
        if: always()
        uses: devellany/send-mail@v1.0.2
          with:
          # Enter SMTP host.
    host: 
    # Enter SMTP port. (defaults to 465)
    port: # optional, default is 465
    # Enter SMTP host account.
    account: 
    # Enter SMTP host account password.
    password: 
    # Enter sender name.
    sender: 
    # Enter sender mail.
    from: 
    # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
    to: 
    # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
    subject: 
    # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
    body: 
    # Enter Content-Type HTTP header. (defaults to 'text/plain')
    contentType: # optional, default is text/plain
    # Attachment files are entered as an array. Required key 'path'. (The prefix 'file://' if you want to read a file)
    attachments: # optional
          
        
        
