name: Email Send
on: push

jobs:
  sendmail:
    runs-on: ubuntu-22.04

    steps:
      - name: Send mail to friend
        run: echo "Hello Friend"

      - name: configuration to send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: ${{secrets.MAIL_ADDRESS}}
          to: ${{secrets.RECIPIENT_EMAIL}}
          subject: Mail Send to use Github Actions
          body: Hello Suresh's ,Congrats on your first email sent from GitHub Actions!
